version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - eed=${eed:-default_value}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django_network
    environment:
      - eed=${eed:-default_value}

volumes:
  postgres_data:

networks:
  django_network:
