yamlname: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Django settings
        run: |
          echo "DEBUG=False" >> .env
          echo "SECRET_KEY='your-secret-key'" >> .env
          echo "DATABASE_URL=sqlite:///$(pwd)/db.sqlite3" >> .env

      - name: Make migrations and migrate
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: python manage.py test notes.tests