name: Django CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/*'
      - 'notes/*'
      - 'users/*'
      - 'adventure_tracker_app/*'
      - '.env'
      - '.flake8'
      - 'requirements.txt'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Django environment variables
      SECRET_KEY: django-insecure-2c(ubr^jlo&=s@a=jxwivc^ynwj(w+(40_0vk849zx(#1e$eed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linters
      run: |
        flake8 .

    - name: Run migrations
      run: |
        python manage.py migrate --settings=adventure_tracker_app.test_settings

    - name: Run tests
      run: |
        python manage.py test notes --settings=adventure_tracker_app.test_settings